### ISSUE TITLE
Please make process.uncaughtException handler optional

### ISSUE THREAD

**Issue by fiznool** [svg-sprite/svg-sprite#23]
I'm using `grunt-svg-sprite` and the task is swallowing my error traces. Could you please make the call to `process.on('uncaughtException', ...)` optional?

Perhaps assume it should be active, unless an option is passed in to disable it.

https://github.com/jkphl/svg-sprite/blob/master/lib/svg-sprite.js#L4

**Comment by jackbrewer** [comment]
Thanks so much for this. I missed the initial notification but will update and let you know if there are any further issues.

Appreciate the update – really enjoying using this module.
