### ISSUE TITLE
1.3.7 Changed CLI behavior

### ISSUE THREAD

**Issue by Imundy** [svg-sprite/svg-sprite#232]
Previously (using 1.3.6) I had an npm script that looked like
`"svg-sprite": "svg-sprite --config=.svg-sprite.json --shape-transform-svgo=.svgo.json ./sprites/svg/*.svg"`
which worked, but now it causes this error to happen:
```
SVGSpriter.add: "sprites/svg/icon.svg" is not the local part of "B:\Jenkins\workspace\Project\sprites\svg\icon.svg"
```
I noticed that removing the initial ./ from ./sprites/svg/*.svg fixed it for me. So now I have 
`"svg-sprite": "svg-sprite --config=.svg-sprite.json --shape-transform-svgo=.svgo.json sprites/svg/*.svg"`

It's a pretty small/trivial difference and I don't really mind, but I just wanted to make sure that this is the desired behavior?

**Comment by jkphl** [comment]
@Imundy Well yeah, I introduced a new feature yesterday ([explicit base path for matching](https://github.com/jkphl/svg-sprite/blob/master/docs/command-line.md#advanced-globbing)) that will be the reason for this behavior. I didn't realize that this could also break things -- I'm sorry for that! I'll see if I can find another solution for that (or at least output a message when the path starts with a dot). Thanks for reporting!

**Comment by Imundy** [comment]
No problem, it was a small thing for me. I think a warning about the dot would suffice. Thanks for the quick response!

**Comment by brandoncash** [comment]
Is it possible to push this feature (explicit base path for matching) off until 2.0.0 so as to avoid breaking semantic versioning?
As it stands, it could potentially break many uses where module versions are not locked and are requesting a version `^1`. Issue #234 is likely to be common for anyone relying on the old API, and it's quite likely that IDs are expected to remain static between builds.

**Comment by Kreeg** [comment]
Hello @jkphl ! It seems like this issue is outdated. Closing it for now.
