### ISSUE TITLE
Multiple sources and ouputs

### ISSUE THREAD

**Issue by on3iro** [svg-sprite/svg-sprite#241]
Hey,

we currently have an issue, where we would like to built sprites from two different directories and import both svg-stylesheets into a "parent" and a "child"-scss file.
The structure looks like this:

```
src/
    img/
      app-components/
          sprite.svg
      app/
          sprite.svg 
    sass/
        main.scss
        _svg-sprite.scss
       app-components/
           components.scss
           _svg-sprite.scss
```

`components.scss` is imported inside `main.scss`. The problem is, that the `%svg-common` extend seems to be overwritten and therefore none of the svgs from the `app-components/_svg-sprite.scss` seem to work because the url-path points to the other sprite.

Is  there a way to configure multiple sources and outputs or to at least configure the scss-placeholder variable? We looked into the documentation and could not find anything regarding multiple sources. (Although I have to admit that the style of the documentation is a bit hard to read - no offense - and so we might have overlooked something)

Thanks in advance and thanks for building this great tool.

**Comment by Kreeg** [comment]
Hi! Thank you for feedback. I personally did this:
```
const paths = {
  critical: '../shop/svg-sprite-icons/critical/**/*.svg',
  mono:     '../shop/svg-sprite-icons/mono/**/*.svg',
  multi:    '../shop/svg-sprite-icons/multi/**/*.svg',
};

const svgoPluginsConfig = {
  critical: [
    {
      name: 'preset-default',
    },
    { name: 'removeAttrs', params: { attrs: ['*:(data-*|style|fill):*'] } },
    'removeScriptElement',
    'removeStyleElement',
    'removeUselessDefs',
    'removeXMLNS',
  ],
  mono: [
    {
      name: 'preset-default',
    },
    'removeStyleElement',
    'removeScriptElement',
    { name: 'removeAttrs', params: { attrs: ['*:(fill|data-*|id|class|style)'] } },
  ],
  multi: [{ name: 'removeScriptElement' }],
};

module.exports = {
  paths,
  svgSpriteTask: (svgType) => {
    return gulp.src(paths[svgType]).pipe(
      gulpSVGSprite({
        shape: {
          transform: [
            {
              svgo: {
                plugins: svgoPluginsConfig[svgType],
              },
            },
          ],
        },
        mode: {
          symbol: {
            inline: true,
            dest:   '.',
            sprite: `sprite.${svgType}.svg`,
            render: {
              css: {
                dest: `sprite.${svgType}.css`,
              }
            }
          },
        },
      }),
    ).pipe(gulp.dest(`../shop/svg-sprite/`));
  },
};
```

This is the configuration for 3 different gulp tasks. Each of them get own icons folder, svg sprite and css file. You can do something like that with scss. 
The multiple sources / outputs seems like a great idea but this can be done by code, like in code above. 
I'm closing this issue, but opening a new one to understand if scss variables is needed by community
