### ISSUE TITLE
`createSprite` task no longer woks and throws an error with mustache

### ISSUE THREAD

**Issue by cosola** [svg-sprite/svg-sprite#282]
I'am no longer able to create a sprite and receive an error message, making reference to the mustach:

```
\Users\SCV\Documents\WebDevLesson\mySite\ytabo-project\node_modules\mustache\mustache.js:226
      throw new Error('Unclosed section "' + openSection[1] + '" at ' + scanner.pos);
      ^
```

The createSprite( ) worked well before a minor modification the template was tried.

```
{{#shapes}}
	{{#first}}    // Including template tag {{#first}} {{/first}}
		.icon {
			background-image: url('/assets/images/sprites/{{{sprite}}}');
		}
	{{/first}}

	.icon--{{base}} {
		width: {{width.outer}}px;
		height: {{height.outer}}px;
		background-position: {{position.relative.xy}};
	}
{{/shapes}}
```

Can a kind soul help me understand what is going on. First time using the package.

Thank you for your help.

SCV

**Comment by XhmikosR** [comment]
mustache doesn't like one of your changes, try removing the comment `// Including template tag {{#first}} {{/first}}`
