### ISSUE TITLE
Unnecessary to add "viewBox" to root SVG in stack mode.

### ISSUE THREAD

**Issue by zhansingsong** [svg-sprite/svg-sprite#303]
As the title says. In addition, it leads to a bug.  
the following **stack mode** output：`stack.sprite.svg`

```html
<svg viewBox="0 0 42 42" 
  xmlns="http://www.w3.org/2000/svg" 
  xmlns:xlink="http://www.w3.org/1999/xlink">
  <style>:root&gt;svg{display:none}:root&gt;svg:target{display:block}</style>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 42 42" id="icon-clear">
     <!--  content -->
  </svg>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 14 24" id="icon-right-arrow">
     <!--  content -->
  </svg>
</svg>
```
when displaying `icon-clear`，it work correctly. 

```css
    background-image: url(/stack.sprite.svg#icon-clear);
```
As `viewBox` is the same as the root SVG's.

but displaying `icon-right-arrow`, it work incorrectly, because it is zoomed out.
```css
    background-image: url(/stack.sprite.svg#icon-clear);
```
 The reason is that `viewBox="0 0 42 42"` attribute of root SVG.  if removing `viewBox="0 0 42 42"`，and everything will work fine.

**source** 

```js
SVGSpriteStack.prototype._buildSVG = function(xmlDeclaration, doctypeDeclaration) {
	var rootAttributes				= _.extend(
		{},
		this.config.svg.rootAttributes,
		{
			viewBox					: '0 0 ' + this.maxDimensions.width + ' ' + this.maxDimensions.height
		}
	),
	svg								= new SVGSprite(this.declaration(this.config.svg.xmlDeclaration, xmlDeclaration), this.declaration(this.config.svg.doctypeDeclaration, doctypeDeclaration), rootAttributes, true, this.config.svg.transform);
	svg.add('<style>:root>svg{display:none}:root>svg:target{display:block}</style>');
	svg.add(pluck(this.data.shapes, 'svg'));

	return svg.toFile(this._spriter.config.dest, this._addCacheBusting(svg));
};

```

to fix the bug

```js
var rootAttributes	= _.extend(
        {},
        {viewBox: '0 0 ' + this.maxDimensions.width + ' ' + this.maxDimensions.height},
	this.config.svg.rootAttributes
);
```

**Comment by patric-eberle** [comment]
Same issue here. If I remove `viewBox` I can use the same sprite for CSS mask and inline. With the viewBox in place, the mask use fails... Seems like this was added because of #73

The solution above works, but it is not possible to remove the attribute entirely this way. I would recommend adding a new option to the stacking options.

**Comment by XhmikosR** [comment]
PRs welcome along with a test case.

**Comment by Arkkimaagi** [comment]
We had this issue too, so I wrote an config option for it. Sadly I think I need guidance or help on writing the tests.
