### ISSUE TITLE
Shape names are empty when using relative path SVGs, which causes svgo to fail rendering optimised icons

### ISSUE THREAD

**Issue by Sidnioulz** [svg-sprite/svg-sprite#326]
### Current behaviour

When using relative paths with `.add`, file paths are modified in such a way that Shapes fail to extract a name for each input SVG. Because shapes don't have names, they don't have an ID, and SVGO generates optimised SVGs into the wrong file path.

### Expected behaviour

Shapes should have a valid name no matter if the input SVG's path is relative or absolute

PR #325 fixes this issue. Note that I have 32 tests passing and 2 failing on my PR and machine, but I also have 32 passing and 2 failing on HEAD on master.

**Comment by Kreeg** [comment]
@Sidnioulz Hello! Which tests are failed?

**Comment by Kreeg** [comment]
@Sidnioulz thank you for your participation :)
