### ISSUE TITLE
gulp & grunt，Is it still valid?

### ISSUE THREAD

**Issue by ZhangChengLin** [svg-sprite/svg-sprite#351]
Do you still care about the maintenance of your other 2 projects?
Are they still valid? The last update was in 2018.

```
https://github.com/jkphl/gulp-svg-sprite
https://github.com/jkphl/grunt-svg-sprite
```

**Comment by zhangchenglin** [comment]
Their last update time puzzled me and wondered if it was still available and new enough.
Especially when I only see them, but not jkphl/svg-sprite.

**Comment by XhmikosR** [comment]
If it works, it works. If something doesn't work, feel free to make a PR and CC me.
