### ISSUE TITLE
Is svg.namespaceIDPrefix doing anything?

### ISSUE THREAD

**Issue by bitstarr** [svg-sprite/svg-sprite#358]
Hi,

I wanted to namespace the ids of my symbols in order to avoid problems. But after fiddling around, I searched the code base of this repo and it seems like this option does nothing!

````
…
svg: {
    xmlDeclaration: false,
    doctypeDeclaration: false,
    namespaceIDs: true,
    namespaceIDPrefix: 'icon-',
    rootAttributes: {
        class: 'sprite'
    }
},
…
````

**Comment by Kreeg** [comment]
Hi. This adds a prefix to all ids inside sprite `lib/svg-sprite/shape.js:703`
