### ISSUE TITLE
Support convertColors.currentColor

### ISSUE THREAD

**Issue by benkeil** [svg-sprite/svg-sprite#359]
It looks like this configuration is not supported.

```
{
  "convertColors": {
    "currentColor": true
  }
}
```

**Comment by christian-reichart** [comment]
Hey @benkeil , doesn't solve the issue, but maye this will help you out: https://github.com/christian-reichart/svg-chameleon . It uses svg-sprite under the hood but you can use css variables for coloring. If you set colors.preserveOriginal to false, it also injects currentColor

**Comment by XhmikosR** [comment]
Please provide more info about how you invoke svg-sprite and any needed files so that we try to reproduce.
