### ISSUE TITLE
Next release date?

### ISSUE THREAD

**Issue by ert78gb** [svg-sprite/svg-sprite#443]
Hello,

I see lots of activity from @XhmikosR in the last month and thanks for it, but the last release was more than 2 years ago.

When do you plan to release a new release date?

**Comment by XhmikosR** [comment]
There's no ETA because there's still quite a few things to address.

@jkphl friendly ping to have a look at the open PRs so that we move forward.

**Comment by ert78gb** [comment]
Don't you wanna release in smaller chunks? I like the smaller releases than the big bums.
And not easy resolve 2 years tech dept.

**Comment by XhmikosR** [comment]
Nah, at this point I'd rather finish with the outstanding issues before v2.0.

**Comment by Kreeg** [comment]
@XhmikosR hello, can you share those issues? I'll check if I can help.

**Comment by XhmikosR** [comment]
Hey, @Kreeg! I'd say at this point we should choose how to proceed with puppeteer in #447.

@ert78gb has made some significant work, it's just that it feels like having puppeteer in dependencies is too much because it's just used in the case where the dimensions cannot be determined.

That being said, I'd be happy to go with puppeteer and see if we can make it optional later.

**Comment by Kreeg** [comment]
@XhmikosR I see no problems with going with the puppeteer since phantomjs was also here only for the dimension checking. Since PhantomJS was deprecated I'd say it's more than OK to make puppeteer optional later and go straight with the working solution now :)

**Comment by XhmikosR** [comment]
The thing is that puppeteer is huge. It just doesn't make sense to have it by default :/

Also, I'm just one person with limited time. If you have time, happy to give you push rights to help with the PRs and further tweaks.

**Comment by Kreeg** [comment]
The definition of "having time" may differ, but since my actual work depends on this project I'll do all my best to help with it.
So, yes. I have time. :)

**Comment by XhmikosR** [comment]
Going to close this since we have already released v2.0.0-beta2. After we finish with tests and covering all modes, we can release v2.0.0 stable.
