### ISSUE TITLE
v2.0 plan

### ISSUE THREAD

**Issue by XhmikosR** [svg-sprite/svg-sprite#446]
1. replace phantomjs with puppeteer **but make it optional**; we need test cases for this to be safe. We have #284 but needs more work
2. replace image-diff with looks-same; we have #417 but needs some work
3. modernize the codebase; I've made #436, which I try to split it in smaller chunks.
5. (maybe slate this to 2.1.0 or 3.0.0) Run transformations in parallel, see #422. This is more noticeable with thousands of SVG files. Right now svgo runs one at a time.
5. reduce lodash usage to the minimum and then see what we can replace the remaining things with; lodash gets so many vulnerabilities due to its popularity and it's a big package.
6. split tests and streamline the fixture/test images filenames
7. (optional) see what else we can drop from dependencies, for example pretty-diff

**Comment by yisibl** [comment]
At the risk of asking, when are you going to release the first beta version?

**Comment by XhmikosR** [comment]
I think we are now close with phantomjs gone, puppeteer also gone (at least from dependencies). I just want the CI to be stable and I'll cut a new 2.0.0-beta1 release.

The other TODO can probably wait.

**Comment by yisibl** [comment]
This is great, bye PhantomJS and Puppeteer!

**Comment by XhmikosR** [comment]
Any help to fix any other issues is welcome BTW :)

After beta1 and assuming we have managed to remove puppeteer from devDependencies too, I'll update the gulp and grunt packages too.

**Comment by Kreeg** [comment]
@XhmikosR but how to deal with screenshot testing without puppeteer in devDependencies?

**Comment by XhmikosR** [comment]
I'm not sure either. Previously we were using svg2png. It's not maintained a lot, but it worked and it's a lot smaller.

Apart from that, I don't have any ideas, sorry :/

**Comment by yisibl** [comment]
I'm not sure I understand correctly, it should be possible to use [sharp](https://github.com/lovell/sharp) to get a screenshot

And then when resvg supports [`<use>` nesting](https://github.com/RazrFalcon/resvg/issues/6#issuecomment-1038125357) we can use resvg to take screenshots too?


I'm still a little confused, is it accurate to get the size of the SVG through the viewBox and width/height properties? Do you need something like [getBBox()](https://developer.mozilla.org/en-US/docs/Web/API/SVGGraphicsElement/getBBox) for the dimensions?

https://github.com/svg-sprite/svg-sprite/blob/1a13903a5dc5ed06eecac394c47f8d9b59e301b7/lib/svg-sprite/shape.js#L513-L532

**Comment by Kreeg** [comment]
@yisibl we're using puppeteer to screnshot both html pages and svg elements as well.
Then when resvg supports `<use>` elements we can minimize puppeteer usage to just html screenshots

**Comment by yisibl** [comment]
@Kreeg OK,  resvg 0.22.0 already supports `<use>` links to `<svg>`, which I will finish in this PR: https://github.com/yisibl/resvg-js/pull/71, and you are ready to upgrade.

**Comment by Kreeg** [comment]
@yisibl cool! thanks!

**Comment by XhmikosR** [comment]
@Kreeg do you think we are ready to release 2.0.0-beta1?

**Comment by Kreeg** [comment]
@XhmikosR yeah I think so.
We should also move #81 and all 2.0 milestone issues to 3.0 I think.

**Comment by XhmikosR** [comment]
Nah, don't worry about milestones, I didn't even know there was one :P I prefer to use Projects.

I'll release 2.0.0-beta1 later today or tomorrow morning.

**Comment by XhmikosR** [comment]
https://github.com/svg-sprite/svg-sprite/releases/tag/v2.0.0-beta1

**Comment by Kreeg** [comment]
Cool!

**Comment by XhmikosR** [comment]
Released v2.0.0-beta2:

* https://packagephobia.com/result?p=svg-sprite@2.0.0-beta2
* https://arve0.github.io/npm-download-size/#svg-sprite@1.5.4
* https://arve0.github.io/npm-download-size/#svg-sprite@2.0.0-beta1
* https://arve0.github.io/npm-download-size/#svg-sprite@2.0.0-beta2

If we remove/replace lodash, we'll save around 1K files :)

Closing this issue since we have individual issues for the remaining things.
