### ISSUE TITLE
[Feature Request] Option to set generated css file name

### ISSUE THREAD

**Issue by T1mL3arn** [svg-sprite/svg-sprite#478]
At this time there is a way to change generated sprite file name, but not the stylesheet file name - it is always(?) `style.css`.

**Comment by jkphl** [comment]
I'm not 100% sure, but this should be possible by configuring a suitable `mode.<mode>.render.css.dest` path (see [Rendering configurations](https://github.com/svg-sprite/svg-sprite/blob/master/docs/configuration.md#rendering-configurations), although the example mentions files with `.html` extension). Please let me know if that's correct.

**Comment by T1mL3arn** [comment]
This indeed works. The documentation looked confusing to me. It has for `mode.<mode>.render` this
```
Example: {css: true, scss: {dest: '_sprite.scss'}}
```
which I interpret as `mode.<mode>.dest` due to `css: true`.

**Comment by jkphl** [comment]
Thanks for letting me (and others) know!
