### ISSUE TITLE
My sprite.svg file isnt loading

### ISSUE THREAD

**Issue by EkramulIslam005** [svg-sprite/svg-sprite#498]
Every time i click the file it loads loads and then it shows up "something went wrong. reload?"

**Comment by EkramulIslam005** [comment]
![Screenshot (42)](https://user-images.githubusercontent.com/86062417/128612419-22633dc0-a5df-468d-b094-b12a39f3e1a2.png)
why it is showing

**Comment by XhmikosR** [comment]
That's normal since that's not how sprites work...

**Comment by EkramulIslam005** [comment]
So what should i do
