### ISSUE TITLE
Fix svgo config after #501

### ISSUE THREAD

**Issue by XhmikosR** [svg-sprite/svg-sprite#523]
Our options `doctypeDeclaration` and `xmlDeclaration` don't work properly after #501.

**Comment by XhmikosR** [comment]
@korki43 do you have any ideas about this? Fixing this issue and perhaps replacing phantom-js are the blocking stuff for releasing v2.0.0 (we use this package in icons)

I have a WIP branch but I don't think it's right https://github.com/svg-sprite/svg-sprite/compare/svgo-config

**Comment by korki43** [comment]
I'll have a look at it.

**Comment by korki43** [comment]
@XhmikosR  What is the exact usage of `config.svg.xmlDeclaration` and `config.svg.doctypeDeclaration`?

**Comment by XhmikosR** [comment]
* https://github.com/svg-sprite/svg-sprite/blob/main/docs/configuration.md#sprite-svg-options
* https://github.com/svg-sprite/svg-sprite/blob/main/bin/config.yaml#L97-L106
* https://github.com/svg-sprite/svg-sprite/pull/501/files?w=1#diff-6d96d7717a777094d3cc507079385cbe3d792d6e64fe1ccba129d9b9348eb76e

Basically it toggles those 2 SVGO plugins. Unsure how to handle this with the plugins system.

Thanks for looking into it and Merry Christmas!
