### ISSUE TITLE
svgo package used is still on v1, but thats deprecated. In this code it uses already v2, but that has not been published. Will you publish a new version?

### ISSUE THREAD

**Issue by maapteh** [svg-sprite/svg-sprite#543]
Hi @XhmikosR i see SVGO is updated in #534. But no new version has been released after this update. So SVGO is still on v1 in your latest version 1.5.3 (`"svgo": "^1.3.2",`). Any plans on publishing a new version which contains this merge? 

`svg-sprite > svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.`

**Comment by XhmikosR** [comment]
I'm aware, it will be released when it's ready.
