### ISSUE TITLE
svg stack doesn't fill all available width and height of img

### ISSUE THREAD

**Issue by jetzeny** [svg-sprite/svg-sprite#615]
I'm exporting svgs from figma and unite in [svg stack](https://simurai.com/blog/2012/04/02/svg-stacks) with gulp-svg-sprite to address later using icons.svg#ID. Html code is: ```<img src="icons.svg#logo" class="svg-logo-dims"/>``` Class "svg-logo-dims" sets width and height, for example: width: 20px; height: 20px for img.

![question](https://user-images.githubusercontent.com/45367541/159127567-df0fc659-e140-4540-89b2-f2328a143622.jpg)

Why my svg doesn't cover 20x20? It's centered in img element with a lot of free space. I have to object-fit: cover to make it look like in figma layout. On the other hand if i insert raw svg in my html, specifying same width and height it would be really 20x20 without free space.

I managed to find a solution. If you delete viewBox of parent svg (~~viewBox="0 0 354 519"~~) in generated icons.svg, child svgs would cover img element properly:

```xml
<?xml version="1.0" encoding="utf-8"?><svg viewBox="0 0 354 519" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><style>:root>svg{display:none}:root>svg:target{display:block}</style><svg>...</svg><svg>...</svg></svg>
```

Why does parent svg has viewBox? Is it supposed?

My svg-sprite settings:

```js
 mode: {
  stack: {
    sprite: "../icons.svg",
    example: {
      dest: "../html-example.html",
    },
  },
},
```

**Comment by jetzeny** [comment]
My svg-sprite settings:
```
 mode: {
          stack: {
            sprite: "../icons.svg",
            example: {
              dest: "../html-example.html",
            },
          },
        },
```

**Comment by Kreeg** [comment]
@jetzeny hi!
I've added tests for stack mode, and it seems they all good. Please provide svg references which are causing the problem, I will add them to tests.

**Comment by jetzeny** [comment]
Icons:
![cart-ico](https://user-images.githubusercontent.com/45367541/159164908-0ba34108-bf27-4a10-9c14-466839659ca9.svg)
![heart-ico](https://user-images.githubusercontent.com/45367541/159164910-b9d945ba-b3d7-4e39-9bf1-8a8b4b0dc17e.svg)
![logo-ico](https://user-images.githubusercontent.com/45367541/159164911-a779e4c5-25e9-45e8-9084-6969b5650947.svg)
![search-ico](https://user-images.githubusercontent.com/45367541/159164912-99926ab3-3531-4714-9fe2-7a3feb41b7e2.svg)
And result after gulp-svg-sprite: 
![icons](https://user-images.githubusercontent.com/45367541/159164946-31777b91-e4e2-4ba1-873d-fa359f6945b5.svg)
As you can see, it took viewBox of third icon and set it to parent svg. For what reason? Because, If you delete 'viewBox="0 0 104 26" ' from parent svg, child svg would have proper sizes.
html:
```
<img src="./img/svg/icons.svg#logo" class="svg-logo-dims" alt="logo" />
<img src="./img/svg/icons.svg#search-ico" class="svg-search-ico-dims" alt="search-ico"/>
<img src="./img/svg/icons.svg#heart-ico" class="svg-heart-ico-dims" alt="heart-ico" />
<img src="./img/svg/icons.svg#cart-ico" class="svg-cart-ico-dims" alt="cart-ico" />
```
CSS:
```
.svg-logo-dims { width: 20px; height: 20px; }
.svg-search-ico-dims { width: 16px; height: 16px; }
.svg-heart-ico-dims { width: 21px; height: 18px; }
.svg-cart-ico-dims { width: 18px; height: 16px; }

```

**Comment by jetzeny** [comment]
> @jetzeny hey can you check if this problem is still exist in branch pr-657 (mentioned in #657)

How do i check it? I'm not very familiar with Git... What i did: git clone svg-sprite in separate folder, git checkout to pr 657, copy resulting content to node_modules->svg-sprite with replacement. Now when i'm running my svg gulp task (which requiring gulp-svg-sprite) i got the error: ```Optimizing "%s" with SVGO failed with error "%s"```
