### ISSUE TITLE
Width and height attributes are not set

### ISSUE THREAD

**Issue by dreit-p** [svg-sprite/svg-sprite#676]
When SVG dimensionAttributes boolean is set to **TRUE** the generated sprite has no height and width attributes on the symbols.
The config is
```JavaScript
.pipe(svgSprite({
	mode: {
		symbol: true
	},
	shape: {
		dimension: {
			attributes: true
		}
	},
	svg: {
		dimensionAttributes: true
	}
}))
```

Input arrow.svg:
```XML
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 34.004 20.997" width="34.004" height="20.997">
	<path d="M4 0l13 12.978L30.008 0l4 4-17 17-17-17z" fill="white" />
</svg>
```

Output:
```XML
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
	<symbol viewBox="0 0 34.004 20.997" id="arrow" xmlns="http://www.w3.org/2000/svg">
		<path d="M4 0l13 12.978L30.008 0l4 4-17 17-17-17z" fill="#fff"></path>
	</symbol>
</svg>
```

**Comment by Kreeg** [comment]
@XhmikosR @jkphl it's strange, but the width and height are settled in symbol mode only when the `inline` config attribute passed (https://github.com/svg-sprite/svg-sprite/blob/d8eed87df8a812852796df5969422caafa637825/docs/configuration.md#defs--symbol-mode). And even then it has zero width and height, and there is no total width/height calculation. I'm sure that this was intended. Do you know why is that?

**Comment by Kreeg** [comment]
@dreit-p the thing is that `symbol` sprite has only symbols, without the references, you need to reference them manually. Technically, this is an empty sprite with the symbols only, so I am sure there is no way to calculate the dimensions of the sprite. I think you just got confused with the hybrid `symbol-view` mode, mentioned here #678 and here #81, which is not implemented yet.

**Comment by mikem33** [comment]
@Kreeg @dreit-p Hi! I needed this to avoid set the width and height of each sprite when using `use` tag. I thought that the dimensionAttributes parameter was meant to this. 
It would be possible to get the width and height attributes from the original image instead of calculate dimensions after?

**Comment by dreit-p** [comment]
Seems I had the same case

**Comment by Kreeg** [comment]
Ok, the bottom line here: you should use `view/css `modes to get proper width/height of generated sprite.
If you have problems with that modes - please open the new issue.
