### ISSUE TITLE
Release 2.0 stable

### ISSUE THREAD

**Issue by Kreeg** [svg-sprite/svg-sprite#698]
Remaining issues and opened PR's:

- [x] #702 
- [x] #693 
- [x] #620 
- [x] #619 
- [x] #653 

@XhmikosR hey! I think this is the final path to the stable release. We probably may skip this PR's and land 2.0 version without them. What do you think?

Fixes #697, #368

**Comment by yisibl** [comment]
Hi, any new developments?

**Comment by yisibl** [comment]
Gosh, please take care of yourself.

**Comment by Kreeg** [comment]
@XhmikosR please take care of yourself. This can wait as long as necessary. The health is the most important thing.

**Comment by XhmikosR** [comment]
@Kreeg could you maybe help out with the release notes? That's what's bugging me more, otherwise cutting a release is a matter of seconds :)

**Comment by Kreeg** [comment]
@XhmikosR yes, of course. I'll do it tonight

**Comment by Kreeg** [comment]
**UI and CLI updates:**

- Added `namespaceIDPrefix` [option](https://github.com/svg-sprite/svg-sprite/blob/main/docs/configuration.md#sprite-svg-options)
- Added `rel="noopener noreferrer"` to all links in generated HTML pages.
- Added `compileAsync` [method](https://github.com/svg-sprite/svg-sprite/blob/main/docs/api.md#svgspritercompileasync-config-)
- Added support for disabling root viewBox attribute in [stack mode](https://github.com/svg-sprite/svg-sprite/blob/main/docs/configuration.md#stack-mode)
- Added ID references substitution in href attributes (earlier worked with `xlink:href` only)
- Dropped support for Node version < 12
- Removed deprecated `transform` [option](https://github.com/svg-sprite/svg-sprite/commit/8c562111046caf5e0e4a9b112262783d1e9e9b32)
- Added milliseconds in logger's output
- Changed SVG dimensions calculation from `phantomjs` to `resvg-js`, dropped `PhantomJS` direct dependency (replaced with resvg-js)
- Fixed rare issue with valid svg files marked as invalid 
- Fixed rare bug with checking if passed `config.log` option is an instance of `winston.Logger`
- Fixed missing shape names when adding input files with a relative path 

**Dev updates**
- All packages (dev and direct) are up-to-date (except for playwright)
- Added code linting (XO)
- Replaced `mocha + should + c8` with `jest` test runner
- Replaced `PhantomJS + image-diff` with `playwright + pixelmatch` as for regression tests
- A lot of docs tweaks
- Massively reduced `lodash` and other direct dependencies. Switched to native js alternatives
- A lot of code refactoring. 
   - Massively switched to async methods whenever possible. 
   - Switched to ES6 classes whenever possible
   - Fixed JSDoc documentations
- Added regression tests for svgs without dimensions
- Added regression tests for all modes
- Added tests and coverage reports to CI (linux, windows support.).
- Added unit tests
- Added dependabot
- Replaced `cssmin` with `csso`


@XhmikosR I hope I covered it all. Pls check on typo and grammar :D

**Comment by Kreeg** [comment]
@XhmikosR hello! Can we land the release? Or should I update changelogs?

**Comment by tutkli** [comment]
Any news on this? Is everyone ok?

**Comment by XhmikosR** [comment]
Sorry for the lack of reply, I missed the notifications. I'll take of it soon, but perhaps after #734 since Node.js is pretty old and we are going to make a new major version now.

I'll use @Kreeg's release notes above as a basis.

**Comment by XhmikosR** [comment]
NVM, I'll release v2.0.0 now and we can make a v3.0.0 later.

**Comment by XhmikosR** [comment]
https://github.com/svg-sprite/svg-sprite/releases/tag/v2.0.0

**Comment by XhmikosR** [comment]
Released https://github.com/svg-sprite/grunt-svg-sprite/releases/tag/v2.0.0 and https://github.com/svg-sprite/gulp-svg-sprite/releases/tag/v2.0.0 too.

**Comment by Kreeg** [comment]
Whohoo!
