### ISSUE TITLE
Update of dependencies in stable version - svgo@1.3.2 is no longer supported

### ISSUE THREAD

**Issue by emilschultz** [svg-sprite/svg-sprite#711]
Hi,
First off, thank you for an awesome package!
Secondly, I can see that the dependencies have been bumped in the beta version, but will there be an update to the dependencies related to the stable version any time soon? 

More specifically `svgo` - We are getting npm WARN `svgo@1.3.2: This SVGO version is no longer supported`.

Best
Emil Schultz
Amedia Utvikling

**Comment by Kreeg** [comment]
@emilschultz Hi! This will be soon fixed in 2.0 stable release #698
