### ISSUE TITLE
SVGO configuration

### ISSUE THREAD

**Issue by alex-belost** [svg-sprite/svg-sprite#723]
SVGO configuration overrides didn't work and it has some problems with SVG optimization. SVGO with default configuration compresses files bit a bit more 

![image](https://user-images.githubusercontent.com/17066351/184669458-4e119359-0d8a-454b-a5fd-026b078054ac.png)

**Comment by taylinr** [comment]
Have the same issue with the following configuration:

`transform: {
        svgo: {
          multipass: true,
          plugins: [
            {
              name: 'preset-default',
              params: {
                overrides: {
                  removeTitle: false,
                  removeDesc: false
                }
              }
            },
          ]
        }
      },`

**Comment by Kreeg** [comment]
@alex-belost @taylinr 
Hello. You need to pass a proper configuration, like this
```
shape: {
    transform: [
      {
        svgo: {
          plugins: [
              {
                name: 'preset-default',
              },
              { name: 'removeAttrs', params: { attrs: ['*:(data-*|style|fill):*'] } },
              'removeScriptElement',
              'removeStyleElement',
              'removeUselessDefs',
              'removeXMLNS',
            ],
        },
      },
    ],
  },
```

Check the configuration params [here](https://github.com/svg/svgo#configuration)

**Comment by Kreeg** [comment]
@alex-belost @taylinr which version do you use?
current stable version has `svgo v1.3.x`, which has different API. If you want to use newer version of svgo - please use current beta version or just wait the v2.0 release #698

**Comment by Kreeg** [comment]
I updated the tests, all the `plugins` configuration goes straight to the SVGO without a modifications. You should either use beta version of `svg-sprite`, or use the `svgo v1` configuration.
