### ISSUE TITLE
Update svgo to v3.x and csso to v5.x

### ISSUE THREAD

**Issue by XhmikosR** [svg-sprite/svg-sprite#741]
https://github.com/svg/svgo/releases/tag/v3.0.0

We need to adapt our code too, PRs welcome!

EDIT: We should also update csso to v5.x after the svgo 3.x update, since svgo 3.x updated to that version too.

**Comment by XhmikosR** [comment]
We should update csso to v5.x after the svgo 3.x update, since svgo 3.x updated to that version too.

**Comment by XhmikosR** [comment]
@Kreeg I released v3.0.0-alpha1. After someone updates these two deps we can release a beta.

Then I think we have the regressions to fix, but unless someone provides a PR with tests and CC's us, not sure how we can fix those...

**Comment by filoxo** [comment]
Can I ask which regressions you're referring to? I'm interested in contributing them if possible, but #773 passes CI so i'm unsure where to find the issues that arise from upgrading. Thanks in advance!

**Comment by Kreeg** [comment]
@filoxo hello! Thanks for offering. There is no regressions or anything, this PR just needs a review from @XhmikosR.

**Comment by XhmikosR** [comment]
Released as `v3.0.0-beta1`. The new csso is quite bigger than 4.x but we can't do a lot about it.
