### ISSUE TITLE
How to replace the value of the fill attribute in the svg image code with any other custom value?

### ISSUE THREAD

**Issue by Syubukov** [svg-sprite/svg-sprite#744]
For example i want replace fill attribute fill="#87B0EE" in svg image code that way that i can have access to it and can change it states via css variables. Like this: fill="var(--color,#87B0EE)". That because shadow-root not allow have access to some tags in svg image code and it does not allow, for example, the path tag to inherit the property of its parent.

I can't find a way how I can replace it with some custom value. (I'm not doing well with javascript).

Im using inline svg and insert it via use tag. Thanks.

**Comment by gynekolog** [comment]
One way you could go is to use `currentColor` and set the icon color with CSS.

svg-sprite.config
```
...
"shape": {
    "transform": [
      {
        "svgo": {
          "plugins": [
            {
              "name": "convertColors",
              "params": {
                "currentColor": true
              }
            }
          ]
        }
      }
    ]
  },
  ...
 ```
  
 css:
```
.your-icon-selector {
  color: #87B0EE;
}
```
