### ISSUE TITLE
i am starting to work on unplugin-svg-sprite project

### ISSUE THREAD

**Issue by yunsii** [svg-sprite/svg-sprite#832]
Plugin wrapper for vite, webpack, nextjs, rollup, esbuild, rspack based on [unplugin](https://github.com/unjs/unplugin).

Welcome anybody interested join the project: [unplugin-svg-sprite](https://github.com/yunsii/unplugin-svg-sprite).

**Comment by yunsii** [comment]
ref: https://github.com/svg-sprite/svg-sprite/issues/380

**Comment by chimok** [comment]
Mmmm... Webpack is dead and there is already resvg since many years. But new options are always good. https://github.com/RazrFalcon/resvg/

**Comment by yunsii** [comment]
CSS icon is a better chioce, I had migrated to this tech.

**Comment by chimok** [comment]
@yunsii Can you explain what you mean with "css icons" for your case? Maybe its interesting for someone come here by search.

**Comment by yunsii** [comment]
Article for CSS icons: https://antfu.me/posts/icons-in-pure-css

You can use it in tailwindcss and unocss as I know:

- https://iconify.design/docs/usage/css/tailwind/
- https://unocss.dev/presets/icons#icons-preset

Also I create a tailwind plugin for better DX(maybe 😂): https://github.com/yunsii/tailwindcss-plugin-iconify
