### ISSUE TITLE
[v2.0.2] - Can we upgrade v2.0.2 to have lodash version that fixes the lodash.trim vulnerability

### ISSUE THREAD

**Issue by classicmike** [svg-sprite/svg-sprite#840]
Hi all.

I would like to introduce a change to bump up the 2.0.2 release of svg-sprite to fix the following vulnerability https://github.com/advisories/GHSA-29mw-wpgm-hmr9

Here is a screenshot of the vulnerability after NPM audit:

<img width="868" alt="Screen Shot 2023-08-25 at 2 04 02 pm" src="https://github.com/svg-sprite/svg-sprite/assets/1841040/4276847e-bb52-4c56-b09d-b6ad4cb9bfee">

My fix will involve replacing the individual lodash packages with 4.,17.21 version of the entire lodash package. It's currently on my own fork here:
https://github.com/classicmike/svg-sprite/commit/f31c8003297b313aa3d2db29cc1cbb8f6be86f3c

Questions on this if we were to go ahead with this fix, where can I redirect my PR to? I'm asking this because it seems like this repo is working towards a version 3 which already has breaking changes. My assumption would be is to create a new branch on this repo based on the v2.0.2 tag then I PR to that new branch and publish a new v2.0.3 release from there.

Anybody managing this project could you please let me know. Thanks.

**Comment by brandonburkett** [comment]
I see this every time we npm install.  Is this project still maintained?

**Comment by chimok** [comment]
@brandonburkett It seems it is because there's a 3.0.0-beta2

**Comment by classicmike** [comment]
@brandonburkett - feel free to download my fork for the timebeing. Long term not interested in maintaining the library myself but I might have to force the issue if no one reply.

**Comment by brandonburkett** [comment]
@classicmike Thank you! Will do that on Monday :)

**Comment by chimok** [comment]
https://github.com/svg-sprite/svg-sprite/pull/850

**Comment by XhmikosR** [comment]
Should be fixed in v2.0.3
