### ISSUE TITLE
Spriter's Shape Transform Method Only Running First Transformation in shape.transform Array. Again

### ISSUE THREAD

**Issue by Divergense** [svg-sprite/svg-sprite#890]
Latest npm available version (2.0.3) has mentioned bug.
This bug described and fixed in details here <https://github.com/svg-sprite/svg-sprite/issues/762>.
But branch 2.x doesn't contain the fixes and hence npm 2.x versions still have this bug.

**Comment by XhmikosR** [comment]
You need to use v3 for this fix. It was only applied to main branch thus only in v3.

Also see the release notes. I don't want having to keep maintaining two branches so at some point soon I'll just publish the current main branch as v3.0.0 stable.

**Comment by XhmikosR** [comment]
@Divergense actually this was easier to cherry pick so I just released 2.0.4.

I really hope this will be the last 2.x release and the next one will be 3.0.0. I also released 3.0.0-rc2 which is the same as rc1 but with Node.js < 18 dropped.
